// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/rmq/publisher.go

// Package rmq is a generated GoMock package.
package rmq

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockAMQPPublisher is a mock of AMQPPublisher interface.
type MockAMQPPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAMQPPublisherMockRecorder
}

// MockAMQPPublisherMockRecorder is the mock recorder for MockAMQPPublisher.
type MockAMQPPublisherMockRecorder struct {
	mock *MockAMQPPublisher
}

// NewMockAMQPPublisher creates a new mock instance.
func NewMockAMQPPublisher(ctrl *gomock.Controller) *MockAMQPPublisher {
	mock := &MockAMQPPublisher{ctrl: ctrl}
	mock.recorder = &MockAMQPPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAMQPPublisher) EXPECT() *MockAMQPPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAMQPPublisher) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAMQPPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAMQPPublisher)(nil).Close))
}

// PublishJSON mocks base method.
func (m *MockAMQPPublisher) PublishJSON(arg0 context.Context, arg1 string, arg2 any, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishJSON", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishJSON indicates an expected call of PublishJSON.
func (mr *MockAMQPPublisherMockRecorder) PublishJSON(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishJSON", reflect.TypeOf((*MockAMQPPublisher)(nil).PublishJSON), arg0, arg1, arg2, arg3)
}
