// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/ride/usecase/ride.go
//
// Generated by this command:
//
//	mockgen -source=pkg/ride/usecase/ride.go -destination=pkg/ride/usecase/ride_mock.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRideUseCase is a mock of RideUseCase interface.
type MockRideUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRideUseCaseMockRecorder
	isgomock struct{}
}

// MockRideUseCaseMockRecorder is the mock recorder for MockRideUseCase.
type MockRideUseCaseMockRecorder struct {
	mock *MockRideUseCase
}

// NewMockRideUseCase creates a new mock instance.
func NewMockRideUseCase(ctrl *gomock.Controller) *MockRideUseCase {
	mock := &MockRideUseCase{ctrl: ctrl}
	mock.recorder = &MockRideUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideUseCase) EXPECT() *MockRideUseCaseMockRecorder {
	return m.recorder
}

// EndRide mocks base method.
func (m *MockRideUseCase) EndRide(c *gin.Context, request EndRideRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndRide", c, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndRide indicates an expected call of EndRide.
func (mr *MockRideUseCaseMockRecorder) EndRide(c, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndRide", reflect.TypeOf((*MockRideUseCase)(nil).EndRide), c, request)
}

// GetRide mocks base method.
func (m *MockRideUseCase) GetRide(c *gin.Context, req GetRideRequest) (*GetRideResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRide", c, req)
	ret0, _ := ret[0].(*GetRideResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRide indicates an expected call of GetRide.
func (mr *MockRideUseCaseMockRecorder) GetRide(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRide", reflect.TypeOf((*MockRideUseCase)(nil).GetRide), c, req)
}

// ListMyRides mocks base method.
func (m *MockRideUseCase) ListMyRides(c *gin.Context, req ListMyRidesRequest) (*ListMyRidesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyRides", c, req)
	ret0, _ := ret[0].(*ListMyRidesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyRides indicates an expected call of ListMyRides.
func (mr *MockRideUseCaseMockRecorder) ListMyRides(c, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyRides", reflect.TypeOf((*MockRideUseCase)(nil).ListMyRides), c, req)
}

// StartRide mocks base method.
func (m *MockRideUseCase) StartRide(c *gin.Context, request StartRideRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRide", c, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRide indicates an expected call of StartRide.
func (mr *MockRideUseCaseMockRecorder) StartRide(c, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRide", reflect.TypeOf((*MockRideUseCase)(nil).StartRide), c, request)
}
